<?php
/**
* @file
* FastImport for commerce price & commerce amounts
*
* Adds a text field when a node is displayed
* so that authenticated users may make notes.
*/


/**
* Implementation of hook_menu().
*/
function fastimport_menu() {

  // Add configuration submenu (? no need in menu, but for Settings from Modules page)
  // $items['admin/commerce/fastimport/config'] = array(
    // 'title' => 'fastimport Settings',
    // 'description' => 'Commerce fastimport shipping method settings.',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('fastimport_settings_form'),
    // 'access arguments' => array('administer site configuration'),
    // 'file' => 'fastimport.admin.inc',
  // );

  // Extra level menu
	// $items['admin/commerce/fastimport'] = array(
		// 'title' => 'Fast Import',
		// 'description' => 'Fast import for Commerce Price by @Lev',
		// 'position' => 'right',
		// 'weight' => -5,
		// 'page callback' => 'system_admin_menu_block_page',
		// 'access arguments' => array('administer site configuration'),
		// 'file' => 'system.admin.inc',
		// 'file path' => drupal_get_path('module', 'system'),
	// );	
	
	// One-page form for admin.. It's
	$items['admin/commerce/fastimport'] = array(
		'title' => 'Fast Import',
		'description' => 'Fast import for Commerce Price by @Lev',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('fastimport_settings_form'),		
		//'page callback' => 'fastimport_import_form',
		'access arguments' => array('administer site configuration'),
		'file' => 'fastimport.admin.inc',
	);

	return $items;
}

function db_exec($query, array $args = array(), array $options = array()) {
  if (empty($options['target'])) {
    $options['target'] = 'default';
  }
  $options['return'] =  Database::RETURN_AFFECTED;

  return Database::getConnection($options['target'])->query($query, $args, $options);
}