<?php

/**
 * Implements hook_init().
 */

function filter_block_init(){

  $patterns = array(
    'katalog/svetilniki*',
    'katalog/lyustry*',
    'katalog/nastolnye-lampy*',
    'katalog/torshery-napolnye*',
    'katalog/bra-nastennye*',
    'katalog/podsvetki-dlya-kartin*',
    'katalog/ulichnye-fonari*',
    'katalog/ulichnye-svetilniki'
  );
  $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));

  foreach ($patterns as $pattern){
  if (drupal_match_path($path, $pattern)) {
      drupal_add_css("#edit-category-wrapper {display: none !important}", 'inline');
    }
  }
  if(drupal_match_path($path, 'strany*')){
    drupal_add_css("#edit-field-strana-proishozhdenija-tid-wrapper {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/hrustalnye')){
    drupal_add_css("#edit-christal {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/svetodiodnye')){
    drupal_add_css("#edit-led {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/kovanye')){
    drupal_add_css("#edit-forged {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/tochechnye')){
    drupal_add_css("#edit-dotted {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/detskie')){
    drupal_add_css("#edit-children {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/vlagozashhishhennye')){
    drupal_add_css("#edit-protect {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/na-solnechnih-batareyah')){
    drupal_add_css("#edit-solar {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/properties/floristika')){
    drupal_add_css("#edit-floristics {display: none !important}", 'inline');
  }
  if(drupal_match_path($path, 'katalog/filter*')){
    drupal_add_css(drupal_get_path('module', 'filter_block'). '/assets/filter_page.css');
  }
  if(drupal_match_path($path, 'katalog/filter/result*')){
    drupal_add_js('(function($) {
    $(function(){
    var form =  document.getElementById("views-exposed-form-product-filter-page");
      $(form).hide();
      $("a.filters").toggle(
        function(){
          $(form).slideDown(100);
        },
       function(){
          $(form).slideUp(100);
       });

       });
    })(jQuery);', 'inline');
  }
}




/**
 * Implements hook_menu().
 */
function filter_block_menu() {

    $items['admin/config/system/config_filter'] = array(
        'title' => 'Блок фильтров',
        'description' => 'Настройка описаний для фильтров',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('filter_block_config_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'filter_block.admin.inc',
    );
    return $items;
}



function filter_block_form_views_exposed_form_alter(&$form, $form_state) {

 if ( $form['#id'] == 'views-exposed-form-product-filter-page') {
    
    $query = db_select('field_data_commerce_price');
    $query->addExpression('MIN(commerce_price_amount)', 'min');
    $query->addExpression('MAX(commerce_price_amount)', 'max');
    $limits = $query->execute()->fetch();

    
    $form['price']['#prefix'] = '<div class="slider-widget-wrapper" data-min="' . ($limits->min/100) . '" data-max="' . ($limits->max/100) . '">';
    $form['price']['#suffix'] = '</div>';    

 
    // Attach js and css
    $form['#attached']['library'][] = array('system', 'ui.slider');
    $form['#attached']['js'][] = drupal_get_path('module', 'filter_block') . '/assets/commerce_slider.js';
    $form['#attached']['css'][] = drupal_get_path('module', 'filter_block') . '/assets/commerce_slider.css';

   /* Скрываем дочерние термины в фильтрах "Мтериал абажура" и "Материал каркаса" */
    module_load_include('php', 'filter_block', 'filter_foreach');

     filter_foreach_termins($form['material_abajura']['#options']);
     filter_foreach_termins($form['material_karkas']['#options']);

    if($form['color_abazhura']) {

       /* Выдёргиваем дополнительные поля таксономии color*/

        $color_abajura = filter_foreach_colors($form['color_abazhura']['#options']);

          $form['color_abazhura'] = array(
                '#type' => 'select',
                '#multiple' => TRUE,
                '#options' => $color_abajura
             );

      /* добавляем див для выбора цвета */
       $form['color_abazhura']['#suffix'] = '<div class="colors"></div>';
    }

    if($form['color_karkas']) {

     $color_metall = filter_foreach_colors($form['color_karkas']['#options']);

         $form['color_karkas'] = array(
                '#type' => 'select',
                '#multiple' => TRUE,
                '#options' => $color_metall
             );

       $form['color_karkas']['#suffix'] = '<div class="colors2"></div>';

      }

     /**
      * Фильтр "Тип лампы" сделаем чекбоксес
      */
     $form['type_lamp']['#type'] = 'checkboxes';
     $form['tsok_type']['#type'] = 'checkboxes';

     // Attach js and css
     drupal_add_css(drupal_get_path('module', 'filter_block').'/assets/filters.css', array(
             'group' => CSS_THEME,
             'media' => 'All',
             'preprocess' => TRUE,
         ));

     drupal_add_js(drupal_get_path('module', 'filter_block').'/assets/filters.js', array(
             'type' => 'file',
             'scope' => 'footer',
             'group' => JS_THEME,
         ));

     /**
      * Дескрипшны
      */
     /* Фильтр "Производитель" */
     $form['#info']['filter-field_brand_tid']['description'] = variable_get('brands');
     /* Фильтр "Длна" */
     $form['#info']['filter-field_dlina_value']['description'] = variable_get('dlina');
     /* Фильтр "Ширина" */
     $form['#info']['filter-field_shirina_value']['description'] = variable_get('shirina');
     /* Фильор Диаметр */
     $form['#info']['filter-field_diametr_value']['description'] = variable_get('diametrs');
     /* Фильтр "Количество лампочек" */
     $form['#info']['filter-field_count_lamp_cult_value']['description'] = variable_get('count_lamp');
     /* Фильтр "Стиль" */
     $form['#info']['filter-field_stil_tid']['description'] = variable_get('styles');
     /* Фильтр "Цвет плафона/абажура" */
     $form['#info']['filter-term_node_tid_depth']['description'] = variable_get('color_plafons');
     /* Фильтр "Цвет маталла" */
     $form['#info']['filter-term_node_tid_depth_1']['description'] = variable_get('color_metalls');
     /* Фльтр "Страна происхождения" */
     $form['#info']['filter-field_strana_proishozhdenija_tid']['description'] = variable_get('strana');
     /* Фильтр "Тип лампы" */
     $form['#info']['filter-type_lamp']['description'] = variable_get('type_lamp');
     /* Фильтр "Тип цколя" */
     $form['#info']['filter-tsok_type']['description'] = variable_get('tsokol');
     /* Фильт "Материал абажура" */
     $form['#info']['filter-term_node_tid_depth_2']['description'] = variable_get('material_abajura');
     /* Фильтр "Материал каркаса" */
     $form['#info']['filter-term_node_tid_depth_3']['description'] = variable_get('material_karkasa');
     /* Фильтр "Напряжение" */
     $form['#info']['filter-voltage']['description'] = variable_get('voltage');
     /* Фильтр "Выступ" */
     $form['#info']['filter-field_rast_ot_steny_value']['description'] = variable_get('vistups');
     /* Фильтр "Высота" */
     $form['#info']['filter-field_vysota_value']['description'] = variable_get('visota');
     /* ильтр "Светодиодные" */
     $form['#info']['filter-led']['description'] = variable_get('leds');
     $form['#info']['filter-dotted']['description'] = variable_get('dotteds');
     $form['#info']['filter-christal']['description'] = variable_get('christals');
     $form['#info']['filter-children']['description'] = variable_get('childrens');
     $form['#info']['filter-forged']['description'] = variable_get('forgeds');
     $form['#info']['filter-solar']['description'] = variable_get('solars');
     $form['#info']['filter-protect']['description'] = variable_get('protects');
     $form['#info']['filter-floristics']['description'] = variable_get('floristics');

  }
}