<?php

function editor_form_alter(&$form, &$form_state, $form_id) {
    if (strpos($form_id, '_node_form') !== FALSE) {

        drupal_add_js('jQuery(document).ready(function(){
            jQuery("textarea#edit-body-und-0-value").markItUp(
                mySettings()
            );
        });', 'inline');

        $path = drupal_get_path('module', 'editor');

        $form['#attached']['js'] = array(
            $path . '/vendor/markitup/jquery.markitup.js',
            $path.'/settings.js'
        );
        $form['#attached']['css'] = array(
            $path.'/vendor/markitup/skins/simple/redactor.css',
            $path.'/vendor/markitup/sets/markitup.css'
        );

        /* Загрузка изображений */
       // drupal_add_js($path.'/vendor/autoupload.js','file');

    }
}