<?php
/**
 * Created by PhpStorm.
 * User: Happensit
 * Date: 13.01.14
 * Time: 9:19
 */

function banner_redirect_form_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == "bunner_node_form") {
    drupal_set_title('Группа баннеров на главной странице');
    //$form['title']['#attributes']['placeholder'] = "Название группы Баннеров";
    drupal_add_css('.vertical-tabs {display: none !important};', array('group' => CSS_THEME, 'type' => 'inline'));
    $form['actions']['submit']['#submit'][] = 'banner_redirect_form_submit';
  }
}

function banner_redirect_form_submit($form, &$form_state) {
  $form_state['redirect'] = '<front>';
  $messages = drupal_get_messages('status');
  drupal_set_message('Баннер на главной обновлён!');
}

function banner_redirect_form_preprocess_page(&$variables) {
  if($variables['is_front']) {
    $bun = array();
    $bunners = node_load_multiple(array(), array('type' => 'bunner'));
    foreach ($bunners as $bunner) {
      if ($bunner->status == 1 && empty($bunner->field_bunner_actual)) {
        $bun[] = $bunner;
      }
    }

    $variables['bunner_image'] = $bun;

  }
}